
[linters]
enable = [
    "copyloopvar",
    "err113",
    "errchkjson",
    "goconst",
    "godot",
    "gofmt",
    "makezero",
    "unconvert",
    "unparam",
    "usestdlibvars"
]

[[issues.exclude-rules]]
path = "(.+)_test\\.go"
linters = [ "err113" ]
